name: rosidl_typesupport_opendds
schedules:
- cron: "0 7 * * SUN"
  displayName: Weekly Sunday
  branches:
    include:
    - master
  always: true

jobs:
- job: Linux
  timeoutInMinutes: 90
  pool:
    vmImage: 'ubuntu-20.04'
  container: objectcomputing/opendds_ros2_foxy:latest
  steps:
  - script: |
      pwd
      echo "agend build directory"
      echo $(Agent.BuildDirectory)
      find $(Agent.BuildDirectory)
    displayName: filesystem check
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*.xml'
      searchFolder: '$(Agent.BuildDirectory)/s/build/test_communication/'
